/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReordenarProdutosIndexRouteImport } from './routes/reordenar-produtos/index'
import { Route as ReordenarCategoriasIndexRouteImport } from './routes/reordenar-categorias/index'
import { Route as GerenciarPedidosIndexRouteImport } from './routes/gerenciar-pedidos/index'
import { Route as ProdutosCriarIndexRouteImport } from './routes/produtos/criar/index'
import { Route as ProdutoslistIndexRouteImport } from './routes/produtos/(list)/index'
import { Route as PedidoslistIndexRouteImport } from './routes/pedidos/(list)/index'
import { Route as ClienteslistIndexRouteImport } from './routes/clientes/(list)/index'
import { Route as CategoriaslistIndexRouteImport } from './routes/categorias/(list)/index'
import { Route as ProdutosEditarProductIdRouteImport } from './routes/produtos/editar/$productId'
import { Route as ClientesVisualizarCustomerIdRouteImport } from './routes/clientes/visualizar/$customerId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReordenarProdutosIndexRoute = ReordenarProdutosIndexRouteImport.update({
  id: '/reordenar-produtos/',
  path: '/reordenar-produtos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReordenarCategoriasIndexRoute =
  ReordenarCategoriasIndexRouteImport.update({
    id: '/reordenar-categorias/',
    path: '/reordenar-categorias/',
    getParentRoute: () => rootRouteImport,
  } as any)
const GerenciarPedidosIndexRoute = GerenciarPedidosIndexRouteImport.update({
  id: '/gerenciar-pedidos/',
  path: '/gerenciar-pedidos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosCriarIndexRoute = ProdutosCriarIndexRouteImport.update({
  id: '/produtos/criar/',
  path: '/produtos/criar/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoslistIndexRoute = ProdutoslistIndexRouteImport.update({
  id: '/produtos/(list)/',
  path: '/produtos/',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoslistIndexRoute = PedidoslistIndexRouteImport.update({
  id: '/pedidos/(list)/',
  path: '/pedidos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteslistIndexRoute = ClienteslistIndexRouteImport.update({
  id: '/clientes/(list)/',
  path: '/clientes/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaslistIndexRoute = CategoriaslistIndexRouteImport.update({
  id: '/categorias/(list)/',
  path: '/categorias/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosEditarProductIdRoute = ProdutosEditarProductIdRouteImport.update({
  id: '/produtos/editar/$productId',
  path: '/produtos/editar/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesVisualizarCustomerIdRoute =
  ClientesVisualizarCustomerIdRouteImport.update({
    id: '/clientes/visualizar/$customerId',
    path: '/clientes/visualizar/$customerId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gerenciar-pedidos/': typeof GerenciarPedidosIndexRoute
  '/reordenar-categorias/': typeof ReordenarCategoriasIndexRoute
  '/reordenar-produtos/': typeof ReordenarProdutosIndexRoute
  '/clientes/visualizar/$customerId': typeof ClientesVisualizarCustomerIdRoute
  '/produtos/editar/$productId': typeof ProdutosEditarProductIdRoute
  '/categorias/': typeof CategoriaslistIndexRoute
  '/clientes/': typeof ClienteslistIndexRoute
  '/pedidos/': typeof PedidoslistIndexRoute
  '/produtos/': typeof ProdutoslistIndexRoute
  '/produtos/criar/': typeof ProdutosCriarIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gerenciar-pedidos': typeof GerenciarPedidosIndexRoute
  '/reordenar-categorias': typeof ReordenarCategoriasIndexRoute
  '/reordenar-produtos': typeof ReordenarProdutosIndexRoute
  '/clientes/visualizar/$customerId': typeof ClientesVisualizarCustomerIdRoute
  '/produtos/editar/$productId': typeof ProdutosEditarProductIdRoute
  '/categorias': typeof CategoriaslistIndexRoute
  '/clientes': typeof ClienteslistIndexRoute
  '/pedidos': typeof PedidoslistIndexRoute
  '/produtos': typeof ProdutoslistIndexRoute
  '/produtos/criar': typeof ProdutosCriarIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gerenciar-pedidos/': typeof GerenciarPedidosIndexRoute
  '/reordenar-categorias/': typeof ReordenarCategoriasIndexRoute
  '/reordenar-produtos/': typeof ReordenarProdutosIndexRoute
  '/clientes/visualizar/$customerId': typeof ClientesVisualizarCustomerIdRoute
  '/produtos/editar/$productId': typeof ProdutosEditarProductIdRoute
  '/categorias/(list)/': typeof CategoriaslistIndexRoute
  '/clientes/(list)/': typeof ClienteslistIndexRoute
  '/pedidos/(list)/': typeof PedidoslistIndexRoute
  '/produtos/(list)/': typeof ProdutoslistIndexRoute
  '/produtos/criar/': typeof ProdutosCriarIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gerenciar-pedidos/'
    | '/reordenar-categorias/'
    | '/reordenar-produtos/'
    | '/clientes/visualizar/$customerId'
    | '/produtos/editar/$productId'
    | '/categorias/'
    | '/clientes/'
    | '/pedidos/'
    | '/produtos/'
    | '/produtos/criar/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/gerenciar-pedidos'
    | '/reordenar-categorias'
    | '/reordenar-produtos'
    | '/clientes/visualizar/$customerId'
    | '/produtos/editar/$productId'
    | '/categorias'
    | '/clientes'
    | '/pedidos'
    | '/produtos'
    | '/produtos/criar'
  id:
    | '__root__'
    | '/'
    | '/gerenciar-pedidos/'
    | '/reordenar-categorias/'
    | '/reordenar-produtos/'
    | '/clientes/visualizar/$customerId'
    | '/produtos/editar/$productId'
    | '/categorias/(list)/'
    | '/clientes/(list)/'
    | '/pedidos/(list)/'
    | '/produtos/(list)/'
    | '/produtos/criar/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GerenciarPedidosIndexRoute: typeof GerenciarPedidosIndexRoute
  ReordenarCategoriasIndexRoute: typeof ReordenarCategoriasIndexRoute
  ReordenarProdutosIndexRoute: typeof ReordenarProdutosIndexRoute
  ClientesVisualizarCustomerIdRoute: typeof ClientesVisualizarCustomerIdRoute
  ProdutosEditarProductIdRoute: typeof ProdutosEditarProductIdRoute
  CategoriaslistIndexRoute: typeof CategoriaslistIndexRoute
  ClienteslistIndexRoute: typeof ClienteslistIndexRoute
  PedidoslistIndexRoute: typeof PedidoslistIndexRoute
  ProdutoslistIndexRoute: typeof ProdutoslistIndexRoute
  ProdutosCriarIndexRoute: typeof ProdutosCriarIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reordenar-produtos/': {
      id: '/reordenar-produtos/'
      path: '/reordenar-produtos'
      fullPath: '/reordenar-produtos/'
      preLoaderRoute: typeof ReordenarProdutosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reordenar-categorias/': {
      id: '/reordenar-categorias/'
      path: '/reordenar-categorias'
      fullPath: '/reordenar-categorias/'
      preLoaderRoute: typeof ReordenarCategoriasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gerenciar-pedidos/': {
      id: '/gerenciar-pedidos/'
      path: '/gerenciar-pedidos'
      fullPath: '/gerenciar-pedidos/'
      preLoaderRoute: typeof GerenciarPedidosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos/criar/': {
      id: '/produtos/criar/'
      path: '/produtos/criar'
      fullPath: '/produtos/criar/'
      preLoaderRoute: typeof ProdutosCriarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos/(list)/': {
      id: '/produtos/(list)/'
      path: '/produtos'
      fullPath: '/produtos/'
      preLoaderRoute: typeof ProdutoslistIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos/(list)/': {
      id: '/pedidos/(list)/'
      path: '/pedidos'
      fullPath: '/pedidos/'
      preLoaderRoute: typeof PedidoslistIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/(list)/': {
      id: '/clientes/(list)/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof ClienteslistIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias/(list)/': {
      id: '/categorias/(list)/'
      path: '/categorias'
      fullPath: '/categorias/'
      preLoaderRoute: typeof CategoriaslistIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos/editar/$productId': {
      id: '/produtos/editar/$productId'
      path: '/produtos/editar/$productId'
      fullPath: '/produtos/editar/$productId'
      preLoaderRoute: typeof ProdutosEditarProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/visualizar/$customerId': {
      id: '/clientes/visualizar/$customerId'
      path: '/clientes/visualizar/$customerId'
      fullPath: '/clientes/visualizar/$customerId'
      preLoaderRoute: typeof ClientesVisualizarCustomerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GerenciarPedidosIndexRoute: GerenciarPedidosIndexRoute,
  ReordenarCategoriasIndexRoute: ReordenarCategoriasIndexRoute,
  ReordenarProdutosIndexRoute: ReordenarProdutosIndexRoute,
  ClientesVisualizarCustomerIdRoute: ClientesVisualizarCustomerIdRoute,
  ProdutosEditarProductIdRoute: ProdutosEditarProductIdRoute,
  CategoriaslistIndexRoute: CategoriaslistIndexRoute,
  ClienteslistIndexRoute: ClienteslistIndexRoute,
  PedidoslistIndexRoute: PedidoslistIndexRoute,
  ProdutoslistIndexRoute: ProdutoslistIndexRoute,
  ProdutosCriarIndexRoute: ProdutosCriarIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
