/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdutosCriarIndexRouteImport } from './routes/produtos/criar/index'
import { Route as ProdutoslistIndexRouteImport } from './routes/produtos/(list)/index'
import { Route as ClienteslistIndexRouteImport } from './routes/clientes/(list)/index'
import { Route as CategoriaslistIndexRouteImport } from './routes/categorias/(list)/index'
import { Route as ProdutosEditarProductIdRouteImport } from './routes/produtos/editar/$productId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosCriarIndexRoute = ProdutosCriarIndexRouteImport.update({
  id: '/produtos/criar/',
  path: '/produtos/criar/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoslistIndexRoute = ProdutoslistIndexRouteImport.update({
  id: '/produtos/(list)/',
  path: '/produtos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteslistIndexRoute = ClienteslistIndexRouteImport.update({
  id: '/clientes/(list)/',
  path: '/clientes/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaslistIndexRoute = CategoriaslistIndexRouteImport.update({
  id: '/categorias/(list)/',
  path: '/categorias/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosEditarProductIdRoute = ProdutosEditarProductIdRouteImport.update({
  id: '/produtos/editar/$productId',
  path: '/produtos/editar/$productId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/produtos/editar/$productId': typeof ProdutosEditarProductIdRoute
  '/categorias/': typeof CategoriaslistIndexRoute
  '/clientes/': typeof ClienteslistIndexRoute
  '/produtos/': typeof ProdutoslistIndexRoute
  '/produtos/criar/': typeof ProdutosCriarIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/produtos/editar/$productId': typeof ProdutosEditarProductIdRoute
  '/categorias': typeof CategoriaslistIndexRoute
  '/clientes': typeof ClienteslistIndexRoute
  '/produtos': typeof ProdutoslistIndexRoute
  '/produtos/criar': typeof ProdutosCriarIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/produtos/editar/$productId': typeof ProdutosEditarProductIdRoute
  '/categorias/(list)/': typeof CategoriaslistIndexRoute
  '/clientes/(list)/': typeof ClienteslistIndexRoute
  '/produtos/(list)/': typeof ProdutoslistIndexRoute
  '/produtos/criar/': typeof ProdutosCriarIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/produtos/editar/$productId'
    | '/categorias/'
    | '/clientes/'
    | '/produtos/'
    | '/produtos/criar/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/produtos/editar/$productId'
    | '/categorias'
    | '/clientes'
    | '/produtos'
    | '/produtos/criar'
  id:
    | '__root__'
    | '/'
    | '/produtos/editar/$productId'
    | '/categorias/(list)/'
    | '/clientes/(list)/'
    | '/produtos/(list)/'
    | '/produtos/criar/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProdutosEditarProductIdRoute: typeof ProdutosEditarProductIdRoute
  CategoriaslistIndexRoute: typeof CategoriaslistIndexRoute
  ClienteslistIndexRoute: typeof ClienteslistIndexRoute
  ProdutoslistIndexRoute: typeof ProdutoslistIndexRoute
  ProdutosCriarIndexRoute: typeof ProdutosCriarIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos/criar/': {
      id: '/produtos/criar/'
      path: '/produtos/criar'
      fullPath: '/produtos/criar/'
      preLoaderRoute: typeof ProdutosCriarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos/(list)/': {
      id: '/produtos/(list)/'
      path: '/produtos'
      fullPath: '/produtos/'
      preLoaderRoute: typeof ProdutoslistIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/(list)/': {
      id: '/clientes/(list)/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof ClienteslistIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias/(list)/': {
      id: '/categorias/(list)/'
      path: '/categorias'
      fullPath: '/categorias/'
      preLoaderRoute: typeof CategoriaslistIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos/editar/$productId': {
      id: '/produtos/editar/$productId'
      path: '/produtos/editar/$productId'
      fullPath: '/produtos/editar/$productId'
      preLoaderRoute: typeof ProdutosEditarProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProdutosEditarProductIdRoute: ProdutosEditarProductIdRoute,
  CategoriaslistIndexRoute: CategoriaslistIndexRoute,
  ClienteslistIndexRoute: ClienteslistIndexRoute,
  ProdutoslistIndexRoute: ProdutoslistIndexRoute,
  ProdutosCriarIndexRoute: ProdutosCriarIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
